<?php

declare(strict_types=1);

namespace PddSdk\Api\Message;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 取消用户的消息服务。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.pmc.user.cancel
 */
final class PddPmcUserCancel extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.pmc.user.cancel',
            name: '取消用户的消息服务',
            category: OfficialCategory::Message,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.pmc.user.cancel',
        );
    }
}
