<?php

declare(strict_types=1);

namespace PddSdk\Api\AfterSales;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 退货入库。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.nextone.logistics.warehouse.update
 */
final class PddNextoneLogisticsWarehouseUpdate extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.nextone.logistics.warehouse.update',
            name: '退货入库',
            category: OfficialCategory::AfterSales,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.nextone.logistics.warehouse.update',
        );
    }
}
