<?php

declare(strict_types=1);

namespace PddSdk\Api\AfterSales;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 用户申请售后时提交的图片凭证。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.refund.images.get
 */
final class PddRefundImagesGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.refund.images.get',
            name: '用户申请售后时提交的图片凭证',
            category: OfficialCategory::AfterSales,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.refund.images.get',
        );
    }
}
