<?php

declare(strict_types=1);

namespace PddSdk\Api\AfterSales;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 售后单详情接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.refund.information.get
 */
final class PddRefundInformationGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.refund.information.get',
            name: '售后单详情接口',
            category: OfficialCategory::AfterSales,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.refund.information.get',
        );
    }
}
