<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\ServiceMarket;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 服务市场订单履约查询。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.servicemarket.contract.search
 */
final class PddServicemarketContractSearch extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.servicemarket.contract.search',
            name: '服务市场订单履约查询',
            category: OfficialCategory::ServiceMarket,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.servicemarket.contract.search',
        );
    }
}
