<?php

declare(strict_types=1);

namespace PddSdk\Api\ServiceMarket;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 交易明细单导出。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.servicemarket.tradelist.get
 */
final class PddServicemarketTradelistGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.servicemarket.tradelist.get',
            name: '交易明细单导出',
            category: OfficialCategory::ServiceMarket,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.servicemarket.tradelist.get',
        );
    }
}
