<?php

declare(strict_types=1);

namespace PddSdk\Api\ServiceMarket;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 月结算账单导出。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.servicemarket.settlementbill.get
 */
final class PddServicemarketSettlementbillGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.servicemarket.settlementbill.get',
            name: '月结算账单导出',
            category: OfficialCategory::ServiceMarket,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.servicemarket.settlementbill.get',
        );
    }
}
