<?php

declare(strict_types=1);

namespace PddSdk\Api\SmsProvider;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 短信明细回执。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.sms.detailbill.push
 */
final class PddSmsDetailbillPush extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.sms.detailbill.push',
            name: '短信明细回执',
            category: OfficialCategory::SmsProvider,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.sms.detailbill.push',
        );
    }
}
