<?php

declare(strict_types=1);

namespace PddSdk\Api\MerchantShipping;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 免密支付状态查询接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.logistics.onlinedelivery.payment.status
 */
final class PddLogisticsOnlinedeliveryPaymentStatus extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.logistics.onlinedelivery.payment.status',
            name: '免密支付状态查询接口',
            category: OfficialCategory::MerchantShipping,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.logistics.onlinedelivery.payment.status',
        );
    }
}
