<?php

declare(strict_types=1);

namespace PddSdk\Api\MerchantShipping;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 获取商家发货地址信息。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.logistics.onlinedelivery.send.address.query
 */
final class PddLogisticsOnlinedeliverySendAddressQuery extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.logistics.onlinedelivery.send.address.query',
            name: '获取商家发货地址信息',
            category: OfficialCategory::MerchantShipping,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.logistics.onlinedelivery.send.address.query',
        );
    }
}
