<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\MerchantShipping;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 商家寄件补贴活动重量申诉接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.logistics.onlinedelivery.subsiby.weight.appeal
 */
final class PddLogisticsOnlinedeliverySubsibyWeightAppeal extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.logistics.onlinedelivery.subsiby.weight.appeal',
            name: '商家寄件补贴活动重量申诉接口',
            category: OfficialCategory::MerchantShipping,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.logistics.onlinedelivery.subsiby.weight.appeal',
        );
    }
}
