<?php

declare(strict_types=1);

namespace PddSdk\Api\Shop;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 店铺信息接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.mall.info.get
 */
final class PddMallInfoGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.mall.info.get',
            name: '店铺信息接口',
            category: OfficialCategory::Shop,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.mall.info.get',
        );
    }
}
