<?php

declare(strict_types=1);

namespace PddSdk\Api\Shop;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 判断是否对商家展示某个通知。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.mall.notification.type.show.check
 */
final class PddMallNotificationTypeShowCheck extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.mall.notification.type.show.check',
            name: '判断是否对商家展示某个通知',
            category: OfficialCategory::Shop,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.mall.notification.type.show.check',
        );
    }
}
