<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\Shop;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 溯源服务商上传溯源码信息。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.trace.source.upload.code.info
 */
final class PddTraceSourceUploadCodeInfo extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.trace.source.upload.code.info',
            name: '溯源服务商上传溯源码信息',
            category: OfficialCategory::Shop,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.trace.source.upload.code.info',
        );
    }
}
