<?php

declare(strict_types=1);

namespace PddSdk\Api\VideoRecommendation;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * vivo视界资源下发。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.vivodeskwindow.queryresources
 */
final class PddVivodeskwindowQueryresources extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.vivodeskwindow.queryresources',
            name: 'vivo视界资源下发',
            category: OfficialCategory::VideoRecommendation,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.vivodeskwindow.queryresources',
        );
    }
}
