<?php

declare(strict_types=1);

namespace PddSdk\Api\Virtual;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 号卡直连处理结果异步通知。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.sim.process.result.notify
 */
final class PddSimProcessResultNotify extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.sim.process.result.notify',
            name: '号卡直连处理结果异步通知',
            category: OfficialCategory::Virtual,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.sim.process.result.notify',
        );
    }
}
