<?php

declare(strict_types=1);

namespace PddSdk\Api\Virtual;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 虚拟类目发货通知接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.virtual.mobile.charge.notify
 */
final class PddVirtualMobileChargeNotify extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.virtual.mobile.charge.notify',
            name: '虚拟类目发货通知接口',
            category: OfficialCategory::Virtual,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.virtual.mobile.charge.notify',
        );
    }
}
