<?php

declare(strict_types=1);

namespace PddSdk\Api\Virtual;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 虚拟游戏类区服列表接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.virtual.game.server.query
 */
final class PddVirtualGameServerQuery extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.virtual.game.server.query',
            name: '虚拟游戏类区服列表接口',
            category: OfficialCategory::Virtual,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.virtual.game.server.query',
        );
    }
}
