<?php

declare(strict_types=1);

namespace PddSdk\Api\Sms;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 根据运单号发短信。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.open.msg.service.send.express.msg
 */
final class PddOpenMsgServiceSendExpressMsg extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.open.msg.service.send.express.msg',
            name: '根据运单号发短信',
            category: OfficialCategory::Sms,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.open.msg.service.send.express.msg',
        );
    }
}
