<?php

declare(strict_types=1);

namespace PddSdk\Api\Marketing;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 限时限量购活动列表查询。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.promotion.limited.discount.list.get
 */
final class PddPromotionLimitedDiscountListGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.promotion.limited.discount.list.get',
            name: '限时限量购活动列表查询',
            category: OfficialCategory::Marketing,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.promotion.limited.discount.list.get',
        );
    }
}
