<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\Marketing;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 限时限量购活动创建接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.promotion.limited.activity.create
 */
final class PddPromotionLimitedActivityCreate extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.promotion.limited.activity.create',
            name: '限时限量购活动创建接口',
            category: OfficialCategory::Marketing,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.promotion.limited.activity.create',
        );
    }
}
