<?php

declare(strict_types=1);

namespace PddSdk\Api\Voucher;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 批量添加卡券。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.voucher.virtual.card.batch.add
 */
final class PddVoucherVirtualCardBatchAdd extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.voucher.virtual.card.batch.add',
            name: '批量添加卡券',
            category: OfficialCategory::Voucher,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.voucher.virtual.card.batch.add',
        );
    }
}
