<?php

declare(strict_types=1);

namespace PddSdk\Api\Voucher;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 卡券API核销券码。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.voucher.realtime.verify.sync
 */
final class PddVoucherRealtimeVerifySync extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.voucher.realtime.verify.sync',
            name: '卡券API核销券码',
            category: OfficialCategory::Voucher,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.voucher.realtime.verify.sync',
        );
    }
}
