<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\Voucher;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 卡券（电子）核销接口（平台生成卡密）。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.voucher.ota.card.verification
 */
final class PddVoucherOtaCardVerification extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.voucher.ota.card.verification',
            name: '卡券（电子）核销接口（平台生成卡密）',
            category: OfficialCategory::Voucher,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.voucher.ota.card.verification',
        );
    }
}
