<?php

declare(strict_types=1);

namespace PddSdk\Api\Voucher;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 平台卡密核销验券。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.voucher.ota.card.prepare.verification
 */
final class PddVoucherOtaCardPrepareVerification extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.voucher.ota.card.prepare.verification',
            name: '平台卡密核销验券',
            category: OfficialCategory::Voucher,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.voucher.ota.card.prepare.verification',
        );
    }
}
