<?php

declare(strict_types=1);

namespace PddSdk\Api\Voucher;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 卡券信息发送接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.voucher.voucher.info.send
 */
final class PddVoucherVoucherInfoSend extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.voucher.voucher.info.send',
            name: '卡券信息发送接口',
            category: OfficialCategory::Voucher,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.voucher.voucher.info.send',
        );
    }
}
