<?php

declare(strict_types=1);

namespace PddSdk\Api\ArkDataTransfer;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 订单列表查询接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.erp.order.list.get
 */
final class PddErpOrderListGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.erp.order.list.get',
            name: '订单列表查询接口',
            category: OfficialCategory::ArkDataTransfer,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.erp.order.list.get',
        );
    }
}
