<?php

declare(strict_types=1);

namespace PddSdk\Api\Ddk;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 批量绑定推广位的媒体id。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ddk.pid.mediaid.bind
 */
final class PddDdkPidMediaidBind extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ddk.pid.mediaid.bind',
            name: '批量绑定推广位的媒体id',
            category: OfficialCategory::Ddk,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ddk.pid.mediaid.bind',
        );
    }
}
