<?php

declare(strict_types=1);

namespace PddSdk\Api\Ddk;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 生成多多进宝频道推广。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ddk.resource.url.gen
 */
final class PddDdkResourceUrlGen extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ddk.resource.url.gen',
            name: '生成多多进宝频道推广',
            category: OfficialCategory::Ddk,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ddk.resource.url.gen',
        );
    }
}
