<?php

declare(strict_types=1);

namespace PddSdk\Api\Ddk;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 创建多多进宝推广位。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ddk.goods.pid.generate
 */
final class PddDdkGoodsPidGenerate extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ddk.goods.pid.generate',
            name: '创建多多进宝推广位',
            category: OfficialCategory::Ddk,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ddk.goods.pid.generate',
        );
    }
}
