<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\Ddk;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 多多客生成单品推广小程序二维码url。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ddk.weapp.qrcode.url.gen
 */
final class PddDdkWeappQrcodeUrlGen extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ddk.weapp.qrcode.url.gen',
            name: '多多客生成单品推广小程序二维码url',
            category: OfficialCategory::Ddk,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ddk.weapp.qrcode.url.gen',
        );
    }
}
