<?php

declare(strict_types=1);

namespace PddSdk\Api\Travel;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 旅游门票区域编码查询。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ticket.areacode.get
 */
final class PddTicketAreacodeGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ticket.areacode.get',
            name: '旅游门票区域编码查询',
            category: OfficialCategory::Travel,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ticket.areacode.get',
        );
    }
}
