<?php

declare(strict_types=1);

namespace PddSdk\Api\Travel;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 旅游门票订单售后结果回调。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ticket.order.refund.notifycation
 */
final class PddTicketOrderRefundNotifycation extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ticket.order.refund.notifycation',
            name: '旅游门票订单售后结果回调',
            category: OfficialCategory::Travel,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ticket.order.refund.notifycation',
        );
    }
}
