<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\Travel;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 旅游门票订单创建异步回调接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ticket.order.create.notifycation
 */
final class PddTicketOrderCreateNotifycation extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ticket.order.create.notifycation',
            name: '旅游门票订单创建异步回调接口',
            category: OfficialCategory::Travel,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ticket.order.create.notifycation',
        );
    }
}
