<?php

declare(strict_types=1);

namespace PddSdk\Api\Travel;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 门票商品新建及更新接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ticket.goods.upload
 */
final class PddTicketGoodsUpload extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ticket.goods.upload',
            name: '门票商品新建及更新接口',
            category: OfficialCategory::Travel,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ticket.goods.upload',
        );
    }
}
