<?php

declare(strict_types=1);

namespace PddSdk\Api\Travel;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 旅游门票商品履约规则修改。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ticket.sku.rule.edit
 */
final class PddTicketSkuRuleEdit extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ticket.sku.rule.edit',
            name: '旅游门票商品履约规则修改',
            category: OfficialCategory::Travel,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ticket.sku.rule.edit',
        );
    }
}
