<?php

declare(strict_types=1);

namespace PddSdk\Api\Logistics;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 获取拼多多标准地址库。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.logistics.address.get
 */
final class PddLogisticsAddressGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.logistics.address.get',
            name: '获取拼多多标准地址库',
            category: OfficialCategory::Logistics,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.logistics.address.get',
        );
    }
}
