<?php

declare(strict_types=1);

namespace PddSdk\Api\Logistics;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * ISV物流轨迹推送消息订阅接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.logistics.isv.trace.notify.sub
 */
final class PddLogisticsIsvTraceNotifySub extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.logistics.isv.trace.notify.sub',
            name: 'ISV物流轨迹推送消息订阅接口',
            category: OfficialCategory::Logistics,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.logistics.isv.trace.notify.sub',
        );
    }
}
