<?php

declare(strict_types=1);

namespace PddSdk\Api\Logistics;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 获取可发货快递接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.logistics.available.company.recommend
 */
final class PddLogisticsAvailableCompanyRecommend extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.logistics.available.company.recommend',
            name: '获取可发货快递接口',
            category: OfficialCategory::Logistics,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.logistics.available.company.recommend',
        );
    }
}
