<?php

declare(strict_types=1);

namespace PddSdk\Api\Logistics;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 物流信息同步。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.tail.express.sync.jt
 */
final class PddTailExpressSyncJt extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.tail.express.sync.jt',
            name: '物流信息同步',
            category: OfficialCategory::Logistics,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.tail.express.sync.jt',
        );
    }
}
