<?php

declare(strict_types=1);

namespace PddSdk\Api\Logistics;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 末端进村物流轨迹同步。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.tail.rural.express.trace.sync
 */
final class PddTailRuralExpressTraceSync extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.tail.rural.express.trace.sync',
            name: '末端进村物流轨迹同步',
            category: OfficialCategory::Logistics,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.tail.rural.express.trace.sync',
        );
    }
}
