<?php

declare(strict_types=1);

namespace PddSdk\Api\DdkTools;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 查询所有授权的多多客订单。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ddk.all.order.list.increment.get
 */
final class PddDdkAllOrderListIncrementGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ddk.all.order.list.increment.get',
            name: '查询所有授权的多多客订单',
            category: OfficialCategory::DdkTools,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ddk.all.order.list.increment.get',
        );
    }
}
