<?php

declare(strict_types=1);

namespace PddSdk\Api\DdkTools;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 拼多多主站频道推广接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ddk.oauth.resource.url.gen
 */
final class PddDdkOauthResourceUrlGen extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ddk.oauth.resource.url.gen',
            name: '拼多多主站频道推广接口',
            category: OfficialCategory::DdkTools,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ddk.oauth.resource.url.gen',
        );
    }
}
