<?php

declare(strict_types=1);

namespace PddSdk\Api\DdkTools;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 多多客已生成推广位信息查询。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ddk.oauth.goods.pid.query
 */
final class PddDdkOauthGoodsPidQuery extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ddk.oauth.goods.pid.query',
            name: '多多客已生成推广位信息查询',
            category: OfficialCategory::DdkTools,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ddk.oauth.goods.pid.query',
        );
    }
}
