<?php

declare(strict_types=1);

namespace PddSdk\Api\DdkTools;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 多多客工具生成单品推广小程序二维码。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ddk.oauth.weapp.qrcode.url.gen
 */
final class PddDdkOauthWeappQrcodeUrlGen extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ddk.oauth.weapp.qrcode.url.gen',
            name: '多多客工具生成单品推广小程序二维码',
            category: OfficialCategory::DdkTools,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ddk.oauth.weapp.qrcode.url.gen',
        );
    }
}
