<?php

declare(strict_types=1);

namespace PddSdk\Api\DdkTools;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 获取订单详情。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.ddk.oauth.order.detail.get
 */
final class PddDdkOauthOrderDetailGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.ddk.oauth.order.detail.get',
            name: '获取订单详情',
            category: OfficialCategory::DdkTools,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.ddk.oauth.order.detail.get',
        );
    }
}
