<?php

declare(strict_types=1);

namespace PddSdk\Api\WaybillPrinting;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 电子面单回传额外运单号。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.fds.waybill.return.slave
 */
final class PddFdsWaybillReturnSlave extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.fds.waybill.return.slave',
            name: '电子面单回传额外运单号',
            category: OfficialCategory::WaybillPrinting,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.fds.waybill.return.slave',
        );
    }
}
