<?php

declare(strict_types=1);

namespace PddSdk\Api\WaybillPrinting;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 根据更新时间查询订单列表。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.fds.order.list.get
 */
final class PddFdsOrderListGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.fds.order.list.get',
            name: '根据更新时间查询订单列表',
            category: OfficialCategory::WaybillPrinting,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.fds.order.list.get',
        );
    }
}
