<?php

declare(strict_types=1);

namespace PddSdk\Api\Store;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 门店组删除门店。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.mall.info.group.remove.store.get
 */
final class PddMallInfoGroupRemoveStoreGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.mall.info.group.remove.store.get',
            name: '门店组删除门店',
            category: OfficialCategory::Store,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.mall.info.group.remove.store.get',
        );
    }
}
