<?php

declare(strict_types=1);

namespace PddSdk\Api\Store;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 开放平台无PoiId创建门店。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.mall.info.store.create.post.nopoi
 */
final class PddMallInfoStoreCreatePostNopoi extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.mall.info.store.create.post.nopoi',
            name: '开放平台无PoiId创建门店',
            category: OfficialCategory::Store,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.mall.info.store.create.post.nopoi',
        );
    }
}
