<?php

declare(strict_types=1);

namespace PddSdk\Api\Store;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 交易二维码-参数注册接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.qrpay.payee.register
 */
final class PddQrpayPayeeRegister extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.qrpay.payee.register',
            name: '交易二维码-参数注册接口',
            category: OfficialCategory::Store,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.qrpay.payee.register',
        );
    }
}
