<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\Order;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 特定类型订单查询接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.order.specific.order.information.get
 */
final class PddOrderSpecificOrderInformationGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.order.specific.order.information.get',
            name: '特定类型订单查询接口',
            category: OfficialCategory::Order,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.order.specific.order.information.get',
        );
    }
}
