<?php

declare(strict_types=1);

namespace PddSdk\Api\Order;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 订单检索接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.order.search.order
 */
final class PddOrderSearchOrder extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.order.search.order',
            name: '订单检索接口',
            category: OfficialCategory::Order,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.order.search.order',
        );
    }
}
