<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\Order;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 根据订单号查询调查问卷和答案。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.survey.query.special.survey
 */
final class PddSurveyQuerySpecialSurvey extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.survey.query.special.survey',
            name: '根据订单号查询调查问卷和答案',
            category: OfficialCategory::Order,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.survey.query.special.survey',
        );
    }
}
