<?php

declare(strict_types=1);

namespace PddSdk\Api\ElectronicWaybill;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 获取所有标准电子面单模板。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.cloudprint.stdtemplates.get
 */
final class PddCloudprintStdtemplatesGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.cloudprint.stdtemplates.get',
            name: '获取所有标准电子面单模板',
            category: OfficialCategory::ElectronicWaybill,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.cloudprint.stdtemplates.get',
        );
    }
}
