<?php

declare(strict_types=1);

namespace PddSdk\Api\ElectronicWaybill;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 云打印机状态查询。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.cloud.printer.status.query
 */
final class PddCloudPrinterStatusQuery extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.cloud.printer.status.query',
            name: '云打印机状态查询',
            category: OfficialCategory::ElectronicWaybill,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.cloud.printer.status.query',
        );
    }
}
