<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\ElectronicWaybill;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 云打印验证码。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.cloud.print.verify.code
 */
final class PddCloudPrintVerifyCode extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.cloud.print.verify.code',
            name: '云打印验证码',
            category: OfficialCategory::ElectronicWaybill,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.cloud.print.verify.code',
        );
    }
}
