<?php

declare(strict_types=1);

namespace PddSdk\Api\ElectronicWaybill;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 电子面单云打印接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.waybill.get
 */
final class PddWaybillGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.waybill.get',
            name: '电子面单云打印接口',
            category: OfficialCategory::ElectronicWaybill,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.waybill.get',
        );
    }
}
