<?php

declare(strict_types=1);

namespace PddSdk\Api\ElectronicWaybill;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 电子面单云打印更新接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.waybill.update
 */
final class PddWaybillUpdate extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.waybill.update',
            name: '电子面单云打印更新接口',
            category: OfficialCategory::ElectronicWaybill,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.waybill.update',
        );
    }
}
