<?php

declare(strict_types=1);

namespace PddSdk\Api\ElectronicWaybill;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 商家取消获取的电子面单号。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.waybill.cancel
 */
final class PddWaybillCancel extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.waybill.cancel',
            name: '商家取消获取的电子面单号',
            category: OfficialCategory::ElectronicWaybill,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.waybill.cancel',
        );
    }
}
