<?php

declare(strict_types=1);

namespace PddSdk\Api\Invoice;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 开票申请单查询。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.invoice.application.query
 */
final class PddInvoiceApplicationQuery extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.invoice.application.query',
            name: '开票申请单查询',
            category: OfficialCategory::Invoice,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.invoice.application.query',
        );
    }
}
