<?php

declare(strict_types=1);

namespace PddSdk\Api\Invoice;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 开票结果回传。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.invoice.detail.upload
 */
final class PddInvoiceDetailUpload extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.invoice.detail.upload',
            name: '开票结果回传',
            category: OfficialCategory::Invoice,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.invoice.detail.upload',
        );
    }
}
