<?php

declare(strict_types=1);

namespace PddSdk\Api\Invoice;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 订单发票冲红。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.invoice.detail.invalid
 */
final class PddInvoiceDetailInvalid extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.invoice.detail.invalid',
            name: '订单发票冲红',
            category: OfficialCategory::Invoice,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.invoice.detail.invalid',
        );
    }
}
