<?php

declare(strict_types=1);

namespace PddSdk\Api\Tools;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 批量数据解密脱敏接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.open.decrypt.mask.batch
 */
final class PddOpenDecryptMaskBatch extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.open.decrypt.mask.batch',
            name: '批量数据解密脱敏接口',
            category: OfficialCategory::Tools,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.open.decrypt.mask.batch',
        );
    }
}
