<?php

declare(strict_types=1);

namespace PddSdk\Api\Tools;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 批量加密。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.open.kms.encrypt.batch
 */
final class PddOpenKmsEncryptBatch extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.open.kms.encrypt.batch',
            name: '批量加密',
            category: OfficialCategory::Tools,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.open.kms.encrypt.batch',
        );
    }
}
