<?php

declare(strict_types=1);

namespace PddSdk\Api\Tools;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 店铺关联关系上报。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.pop.mall.bind.relation.report
 */
final class PddPopMallBindRelationReport extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.pop.mall.bind.relation.report',
            name: '店铺关联关系上报',
            category: OfficialCategory::Tools,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.pop.mall.bind.relation.report',
        );
    }
}
