<?php

declare(strict_types=1);

namespace PddSdk\Api\Tools;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 获取店铺关联ticket。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.pop.mall.bind.ticket.get
 */
final class PddPopMallBindTicketGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.pop.mall.bind.ticket.get',
            name: '获取店铺关联ticket',
            category: OfficialCategory::Tools,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.pop.mall.bind.ticket.get',
        );
    }
}
