<?php

declare(strict_types=1);

namespace PddSdk\Api\Finance;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 商家货款日账单下载链接查询接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.finance.balance.daily.bill.url.get
 */
final class PddFinanceBalanceDailyBillUrlGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.finance.balance.daily.bill.url.get',
            name: '商家货款日账单下载链接查询接口',
            category: OfficialCategory::Finance,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.finance.balance.daily.bill.url.get',
        );
    }
}
