<?php

declare(strict_types=1);

namespace PddSdk\Api\International;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 海淘服务商上传商品备案信息。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.customs.send.goods.record
 */
final class PddCustomsSendGoodsRecord extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.customs.send.goods.record',
            name: '海淘服务商上传商品备案信息',
            category: OfficialCategory::International,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.customs.send.goods.record',
        );
    }
}
