<?php

declare(strict_types=1);

namespace PddSdk\Api\International;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 保税仓信息查询接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.mall.info.bonded.warehouse.get
 */
final class PddMallInfoBondedWarehouseGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.mall.info.bonded.warehouse.get',
            name: '保税仓信息查询接口',
            category: OfficialCategory::International,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.mall.info.bonded.warehouse.get',
        );
    }
}
