<?php

declare(strict_types=1);

namespace PddSdk\Api\International;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 同步海淘订单申报失败情况。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.oversea.declaration.fail.notify
 */
final class PddOverseaDeclarationFailNotify extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.oversea.declaration.fail.notify',
            name: '同步海淘订单申报失败情况',
            category: OfficialCategory::International,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.oversea.declaration.fail.notify',
        );
    }
}
