<?php

declare(strict_types=1);

namespace PddSdk\Api\International;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 获取多多国际清关材料。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.oversea.clearance.get
 */
final class PddOverseaClearanceGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.oversea.clearance.get',
            name: '获取多多国际清关材料',
            category: OfficialCategory::International,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.oversea.clearance.get',
        );
    }
}
