<?php

declare(strict_types=1);

namespace PddSdk\Api\WeMedia;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 多多视频商家上传视频分片初始化接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.live.video.mall.upload.part.init
 */
final class PddLiveVideoMallUploadPartInit extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.live.video.mall.upload.part.init',
            name: '多多视频商家上传视频分片初始化接口',
            category: OfficialCategory::WeMedia,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.live.video.mall.upload.part.init',
        );
    }
}
