<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\WeMedia;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 多多视频商家上传视频分片完成接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.live.video.mall.upload.part.complete
 */
final class PddLiveVideoMallUploadPartComplete extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.live.video.mall.upload.part.complete',
            name: '多多视频商家上传视频分片完成接口',
            category: OfficialCategory::WeMedia,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.live.video.mall.upload.part.complete',
        );
    }
}
