<?php

declare(strict_types=1);

namespace PddSdk\Api\WeMedia;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 查询商家视频的审核状态。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.live.video.mall.querymallvideoauditstatus
 */
final class PddLiveVideoMallQuerymallvideoauditstatus extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.live.video.mall.querymallvideoauditstatus',
            name: '查询商家视频的审核状态',
            category: OfficialCategory::WeMedia,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.live.video.mall.querymallvideoauditstatus',
        );
    }
}
