<?php

declare(strict_types=1);
/**
 * This file is part of Pinduoduo Open Platform SDK for PHP.
 *
 * @link     https://github.com/whalesky-labs/pdd-sdk-php
 * @document https://github.com/whalesky-labs/pdd-sdk-php
 * @contact  westng
 * @license  https://github.com/whalesky-labs/pdd-sdk-php#license
 */

namespace PddSdk\Api\Warehouse;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 根据商品id查询sku信息。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.stock.goods.id.to.sku.query
 */
final class PddStockGoodsIdToSkuQuery extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.stock.goods.id.to.sku.query',
            name: '根据商品id查询sku信息',
            category: OfficialCategory::Warehouse,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.stock.goods.id.to.sku.query',
        );
    }
}
