<?php

declare(strict_types=1);

namespace PddSdk\Api\Warehouse;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 创建货品。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.stock.ware.create
 */
final class PddStockWareCreate extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.stock.ware.create',
            name: '创建货品',
            category: OfficialCategory::Warehouse,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.stock.ware.create',
        );
    }
}
