<?php

declare(strict_types=1);

namespace PddSdk\Api\Warehouse;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 编辑货品。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.stock.ware.update
 */
final class PddStockWareUpdate extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.stock.ware.update',
            name: '编辑货品',
            category: OfficialCategory::Warehouse,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.stock.ware.update',
        );
    }
}
