<?php

declare(strict_types=1);

namespace PddSdk\Api\Warehouse;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 货品仓库库存信息查询。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.stock.ware.warehouse.query
 */
final class PddStockWareWarehouseQuery extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.stock.ware.warehouse.query',
            name: '货品仓库库存信息查询',
            category: OfficialCategory::Warehouse,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.stock.ware.warehouse.query',
        );
    }
}
