<?php

declare(strict_types=1);

namespace PddSdk\Api\Goods;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 删除草稿接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.delete.draft.commit
 */
final class PddDeleteDraftCommit extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.delete.draft.commit',
            name: '删除草稿接口',
            category: OfficialCategory::Goods,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.delete.draft.commit',
        );
    }
}
