<?php

declare(strict_types=1);

namespace PddSdk\Api\Goods;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 生成商家自定义的规格。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.goods.spec.id.get
 */
final class PddGoodsSpecIdGet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.goods.spec.id.get',
            name: '生成商家自定义的规格',
            category: OfficialCategory::Goods,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.goods.spec.id.get',
        );
    }
}
