<?php

declare(strict_types=1);

namespace PddSdk\Api\Goods;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 标品搜索接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.goods.spu.search
 */
final class PddGoodsSpuSearch extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.goods.spu.search',
            name: '标品搜索接口',
            category: OfficialCategory::Goods,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.goods.spu.search',
        );
    }
}
