<?php

declare(strict_types=1);

namespace PddSdk\Api\Goods;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 商品上架状态设置。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.goods.sale.status.set
 */
final class PddGoodsSaleStatusSet extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.goods.sale.status.set',
            name: '商品上架状态设置',
            category: OfficialCategory::Goods,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.goods.sale.status.set',
        );
    }
}
