<?php

declare(strict_types=1);

namespace PddSdk\Api\Goods;

use PddSdk\Api\ApiMetadata;
use PddSdk\Api\OfficialCategory;
use PddSdk\Client\RpcRequest;

/**
 * 按id获取商品运费模版接口。
 *
 * @generated by scripts/generate-api-classes.php
 * @see https://open.pinduoduo.com/application/document/api?id=pdd.one.express.cost.template
 */
final class PddOneExpressCostTemplate extends RpcRequest
{
    public static function metadata(): ApiMetadata
    {
        return new ApiMetadata(
            type: 'pdd.one.express.cost.template',
            name: '按id获取商品运费模版接口',
            category: OfficialCategory::Goods,
            documentUrl: 'https://open.pinduoduo.com/application/document/api?id=pdd.one.express.cost.template',
        );
    }
}
